require("lib/kathy/ext/string.js")
require("lib/kathy/kathy.js")
require("lib/kathy/controller.js")
require("lib/kathy/event.js")
require("lib/kathy/ui.js")
require("lib/kathy/ui/chatlog.js")
require("lib/kathy/ui/userlist.js")
require("lib/kathy/ui/login.js")
require("lib/kathy/ui/input.js")
require("lib/kathy/ui/error.js")
require("lib/kathy/client.js")

$(function() { Kathy.UI.init() })